### ISSUE TITLE
Failed to run setup script

### ISSUE THREAD

**Issue by sergei** [hatlabs/SH-RPi-daemon#116]
## 🐛 Bug Report
I ran the command 
`$ curl -L     https://raw.githubusercontent.com/hatlabs/SH-RPi-daemon/main/install-online.sh     | sudo bash`

With presented choices, chosen only RTC support. 

Here is the script output:

```bash
Enabling I2C
Installing the GPIO poweroff detection overlay
Installing PCF8563 real-time clock device overlay
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  fake-hwclock
0 upgraded, 0 newly installed, 1 to remove and 219 not upgraded.
After this operation, 32.8 kB disk space will be freed.
(Reading database ... 52768 files and directories currently installed.)
Removing fake-hwclock (0.11+rpt1) ...
Processing triggers for man-db (2.8.5-2) ...
Synchronizing state of fake-hwclock.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable fake-hwclock
Unit /etc/systemd/system/fake-hwclock.service is masked, ignoring.
DONE. Reboot the apply the new settings.
/tmp/SH-RPi-daemon-gL5rH6VS/SH-RPi-daemon-main
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pip is already the newest version (18.1-5+rpt1).
0 upgraded, 0 newly installed, 0 to remove and 219 not upgraded.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /tmp/SH-RPi-daemon-gL5rH6VS/SH-RPi-daemon-main
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-h4lfsn04/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-h4lfsn04/
```

### Environment

* OS: [e.g. Linux / Windows / macOS]
Linux ottopi 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l GNU/Linux

* Python version, get it with:

```bash
$ python --version
Python 2.7.16
$ python3 --version
Python 3.7.3
pi@ottopi:/tmp $ 
```

**Comment by sergei** [comment]
It turned to be that this SW requires at least Python 3.9. After upgrading Python the installation script has finished succesfully.

**Comment by mairas** [comment]
Thank you for the report. I'll actually reopen the issue because I've heard somebody else have a similar problem and there shouldn't be anything in the daemon that would absolutely require py3.9.
